<?php

namespace App\SystemPrompts;

class Prompts
{
    public static function jsonPrompt(): string
    {
        return
            'Parse all the given sentences into this JSON format. If you are unable to parse certain fields, set the value to null.
            The amounts should be clamped between 0 and 10. If the amount is beyond this range, set it to the nearest valid value.
            Do not use special characters, escape characters, newlines (\n), and do not format the JSON using backticks (`). Just give the JSON object.
            The following items are valid for RequestedItem and OfferedItem. Try to match the item as closely as possible to one of these:
            Wood, Lenses, Clay, Gold, Steel, Insulation, Fertilizer, Stone
        {
            "TargetName": "(Azari/Beluga/Cinatu)", //Cinatu may not always be recognised. If you hear something similar, fill in Cinatu (e.g: tribe see or sona tu etc)
            "OriginName": "Azari", //default is Azari
            "RequestedItem": "Item Name",
            "RequestedAmount": 0,
            "OfferedItem": "Item Name",
            "OfferedAmount": 0
        }';
    }

    public static function dealSystemPrompt(): string
    {
        return 'You are a human player in a negotiation game responding to another player. Do not use special characters, escape characters, newlines (\n) or emoji in your response. Always respond in English';
    }

    public static function acceptDealPrompt(array $dealData): string
    {
        //TODO: Implement the tribe name and reason for accepting the deal
        $tribe = "Azari";
        return
            $tribe . ' requested ' . $dealData['RequestedAmount'] . ' ' . $dealData['RequestedItem'] . ' in exchange for your ' . $dealData['OfferedAmount'] . ' ' . $dealData['OfferedItem'] .
            'Write a response to accept the following deal from the ' . $tribe . ' tribe leader. Use a ' . $dealData['speakerStyle'] . ' tone in your response.
            You are accepting the deal for the following reason: ' . $dealData['reason'] . '. Include this reason in your response.';
    }

    public static function rejectDealPrompt(array $dealData): string
    {
        //TODO: Implement the tribe name
        $tribe = "Azari";
        return
            $tribe . ' requested ' . $dealData['RequestedAmount'] . ' ' . $dealData['RequestedItem'] . ' in exchange for their ' . $dealData['OfferedAmount'] . ' ' . $dealData['OfferedItem'] .
            'Write a response to reject the following deal from the ' . $tribe . ' tribe leader. Use a ' . $dealData['speakerStyle'] . ' tone in your response.
            You are refusing the deal for the following reason: ' . $dealData['reason'] . '. Include this reason in your response.';
    }

    /**
     * Generate a counter offer prompt to propose a new deal to the human player
     *
     * @param array $dealData
     * @return string
     */
    public static function counterOfferPrompt(array $dealData): string
    {
        //TODO: Implement the tribe name
        $tribe = "Azari";
        //the $dealData contains a new offer, coming from the AI.
        // It has already been generated by the algorithm and needs a response from the AI.
        return
            "You are proposing a counter offer to the " . $tribe . " tribe leader. You declined for the following reason: "
            . $dealData['reason'] . ". Your new proposal is " . $dealData['OfferedAmount'] . " " . $dealData['OfferedItem'] . " in exchange for "
            . $dealData['RequestedAmount'] . " " . $dealData['RequestedItem'] . ". Write a response to the tribe leader in a " . $dealData['speakerStyle']
            . " tone. Mention that you are declining their offer and presenting the above as an alternative in the speaker's style.
            Be creative in your response, but keep it limited to three sentences.";
    }

    public static function tradeChatPrompt(array $dealData): string
    {
        //the trade chat prompt is used to generate a chat dialogue between the AI and the human player.
        //It generates a chat dialogue based on the trade offer to simulate a negotiation.
        return "Generate a message that you, leader of the " . $dealData['originName'] . " will use to tell another human player (from the "
            . $dealData['targetName'] . " tribe) about what you are offering them. You are offering: "
            . $dealData['OfferedAmount'] . " " . $dealData['OfferedItem'] . " in exchange for " . $dealData['RequestedAmount'] . " " . $dealData['RequestedItem']
            . ". Use a " . $dealData['speakerStyle'] . " tone in your dialogue.";
    }

}
